In [32]:
import pandas as pd
import numpy as np

#for importing libraries

In [33]:
data = pd.read_csv('Sales Data.csv')

#for loading data

In [34]:
data.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,"$5,320",180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,"$7,896",94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,"$4,501",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,"$12,726",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,"$13,685",184

In [35]:
data.info()
# for loading all details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   object
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: int64(1), object(5)
memory usage: 51.4+ KB

In [36]:
data.isnull().sum()
#no missing values

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

In [37]:
data.duplicated().sum()
# no duplicate values

np.int64(0)

In [38]:
for col in data.columns:
  data.rename(columns={col:col.lower().replace(' ','_')},inplace=True)
data.columns
# correcting the column names

Index(['sales_person', 'country', 'product', 'date', 'amount',
       'boxes_shipped'],
      dtype='object')

In [39]:
data["date"] = pd.to_datetime(data.date)
#fixxing date format

In [40]:
data["amount"] = data.amount.str.replace('[$,]','',regex=True).astype(float)
#fixing amount column to make it in float

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sales_person   1094 non-null   object
 1   country        1094 non-null   object
 2   product        1094 non-null   object
 3   date           1094 non-null   datetime64[ns]
 4   amount         1094 non-null   float64
 5   boxes_shipped  1094 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 51.4+ KB

In [42]:
data

,sales_person,country,product,date,amount,boxes_shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184
...,...,...,...,...,...,...
1089,Karlen McCaffrey,Australia,Spicy Special Slims,2022-05-17,4410.0,323
1090,Jehu Rudeforth,USA,White Choc,2022-06-07,6559.0,119
1091,Ches Bonnell,Canada,Organic Choco Syrup,2022-07-26,574.0,217
1092,Dotty Strutley,India,Eclairs,2022-07-28,2086.0,384
1093,Karlen McCaffrey,India,70% Dark Bites,2022-05-23,5075.0,344

All fixed